# Use the official Node.js image as the base image
FROM node:18.16.0-alpine3.18

# Set the working directory in the container
WORKDIR /react-app

# Copy the rest of the application code, and specifically - only .env.dev
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the entire React app code
COPY . .

# Expose the port that the React app will run on
EXPOSE 3000

# Start the React app in development mode
CMD ["npm", "start"]