version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: admin
    #  MONGO_INITDB_ROOT_PASSWORD: pass
    restart: always
    ports:
      - "27017:27017"

  node-web-server:
    build:
      context: .\api
      dockerfile: .\Dockerfile.dev
    container_name: node-web-server
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  react-app:
    build:
      context: .\client
      dockerfile: .\Dockerfile.dev
    container_name: react-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - node-web-server
